@host=https://localhost:7194
@FormId=b7a6c87c-553d-4a13-ab0d-b8d7f576e8c9

### Call Get All
GET {{host}}/api/form/
Content-Type: application/json

### Call Get one

GET {{host}}/api/form/{{FormId}}
Content-Type: application/json

### Call Exists

GET {{host}}/api/form/exists/{{FormId}}
Content-Type: application/json